# .golangci.yml
version:
   value : 2
run:
  go: "1.24"
  timeout: 5m
  issues-exit-code: 1
  tests: true
#  build-tags:
#    - integration

linters:
  disable:
    - gomoddirectives
    - godot
  settings:
    depguard:
      rules:
        Main:
          allow:
            - $standard
            - "github.com/lalbers/irr/pkg"
            - "github.com/spf13/cobra"
            - "github.com/spf13/pflag"
            - "os"
            - "fmt"
            - "log"
            - "strings"
        Pkg:
          allow:
            - $standard
            - "github.com/lalbers/irr/pkg"
            - "helm.sh/helm/v3"
            - "sigs.k8s.io/yaml"
            - "gopkg.in/yaml.v3"
            - "github.com/pkg/errors"
        Test:
          allow:
            - $standard
            - "github.com/lalbers/irr/pkg"
            - "github.com/stretchr/testify"
            - "helm.sh/helm/v3"
            - "sigs.k8s.io/yaml"
            - "gopkg.in/yaml.v3"
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    lll:
      line-length: 140
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
  # Moving exclude rules under linters as a possibility
  # (Documentation unclear, but 'issues' didn't work)
  # exclude-rules: # This might belong here? Check schema/docs if fails.
    # - path: _test\\.go
    #   linters:
    #     - revive
    #   text: "stutters"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # Regex for paths to exclude from analysis
    - "zz_generated.*\\.go" # Exclude auto-generated files
    - "pkg/registrymapping/" # Exclude specific directory

output:
  # Removing keys that seem invalid in config file format
  # format: colored-line-number
  # print-issued-lines: true
  # print-linter-name: true
  # sort-results: true
  # Keep output section minimal or empty if defaults are okay
  # If specific format needed, verify exact key name from documentation / schema
