name: "irr"
version: "0.0.4"
usage: "A Helm plugin for inspecting and validating image references in releases"
description: |-
  This plugin helps inspect and validate image references in Helm releases,
  ensuring proper image tag usage and registry configurations.
command: "$HELM_PLUGIN_DIR/bin/irr"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
useTunnel: true
