name: "irr"
version: "0.0.8"
usage: "Inspect, Override, and Validate image references in Helm charts and releases"
description: |-
  IRR (Image Relocation and Rewrite) is a tool for Helm charts that helps:

  - inspect: Analyze a chart or release to identify image references
  - override: Generate override values to redirect images to a private registry
  - validate: Test that a chart renders correctly with generated overrides

  Examples:
    $ helm irr inspect my-release
    $ helm irr override my-release --target-registry registry.local
    $ helm irr validate my-release -f my-release-overrides.yaml
command: "$HELM_PLUGIN_DIR/bin/irr"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
useTunnel: true
