[project]
name = "registry-rewrite"
version = "0.0.14"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml>=6.0.1",
    "ratelimit>=2.2.1",
    "requests>=2.32.3"
]
