apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deep-nesting
  labels:
    app: deep-nesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-nesting
  template:
    metadata:
      labels:
        app: deep-nesting
    spec:
      containers:
        - name: deep-nested
          image: "{{ .Values.level1.level2.level3.level4.level5.image.registry }}/{{ .Values.level1.level2.level3.level4.level5.image.repository }}:{{ .Values.level1.level2.level3.level4.level5.image.tag }}"
        - name: frontend
          image: "{{ .Values.services.frontend.primaryContainer.image.registry }}/{{ .Values.services.frontend.primaryContainer.image.repository }}:{{ .Values.services.frontend.primaryContainer.image.tag }}" 