apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-nginx"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image_to_process.repository }}:{{ .Values.image_to_process.tag }}" 