apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-parent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-parent
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-parent
    spec:
      containers:
      - name: parent
        image: "{{ .Values.parentAppImage.repository }}:{{ .Values.parentAppImage.tag }}"
        imagePullPolicy: {{ .Values.parentAppImage.pullPolicy }}
        ports:
        - containerPort: 80 