# Test various image reference patterns
image:
  repository: docker.io/nginx
  tag: latest
  pullPolicy: IfNotPresent

explicitRegistry:
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: 1.23.1

quayImage:
  image:
    registry: quay.io
    repository: prometheus/node-exporter
    tag: v1.3.1

stringImage:
  image: "docker.io/busybox:latest"

nestedChart:
  subcomponent:
    image:
      repository: redis
      tag: 6.2.7
      # imageString: redis:6.2.7

digestImage:
  image:
    registry: quay.io
    repository: prometheus/prometheus
    tag: v2.45.0@sha256:2c6c2a0e0d2d0a4d9b36c598c6d4310c0eb9b5aa0f6b3d4554be3c8f7a8c8f8 